### ISSUE TITLE
Error with Node - v12.8.0 

### ISSUE THREAD

**Issue by meabed** [jeffijoe/typesync#38] opened 2019-08-12 20:25 UTC
I have typesync version 0.6.0
```
$ npm list -g --depth 0 | grep typesync
├── typesync@0.6.0
```
I recently upgraded my node version to latest 12.8.0, When i run typesync i get the below error:
```
$ typesync
»  TypeSync v0.6.0
⠋  Syncing type definitions in package.json...events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Gunzip.onerror (_stream_readable.js:744:7)
    at Gunzip.emit (events.js:203:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:173:8) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

I am not sure if thats the root cause is nodejs version and zlib changes or something else changed?

**Comment by jeffijoe** [comment] 2019-08-12 20:27
Duplicate of #37

**Closed by jeffijoe** 2019-08-12 20:27 UTC

**Comment by MGH2558** [comment] 2022-02-17 09:07
This problem was solved for me when I deleted the whole directory of the project and cloned it again and followed the setup instructions of the project.

BTW, I had problems with running the project(my machine stopped responding and I had to reset it manually) before facing this error. Hence, I guess the problem is caused by a file corruption or something.
